# Generated by Django 5.2 on 2025-06-19 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_core_website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='useranalysis',
            name='elements_to_take',
        ),
        migrations.AddField(
            model_name='customuser',
            name='health_notes',
            field=models.TextField(blank=True, help_text='Хронические заболевания, аллергии и т.д.', null=True, verbose_name='Заметки о здоровье'),
        ),
        migrations.AddField(
            model_name='element',
            name='manufacturers',
            field=models.ManyToManyField(blank=True, related_name='elements', to='bio_core_website.manufacturer', verbose_name='Производители'),
        ),
        migrations.AddField(
            model_name='element',
            name='measurement_unit',
            field=models.CharField(blank=True, help_text='нг/мл, мкг, мг и т.д.', max_length=20, null=True, verbose_name='Единица измерения'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание производителя'),
        ),
        migrations.AddField(
            model_name='useranalysis',
            name='analysis_data',
            field=models.JSONField(blank=True, help_text='Структурированные данные анализов', null=True, verbose_name='Данные анализов'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский'), ('O', 'Другой')], max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='useranalysis',
            name='analysis_file',
            field=models.FileField(blank=True, help_text='Загрузите файл с результатами ваших анализов', null=True, upload_to='user_analyses/%Y/%m/%d/', verbose_name='Файл с анализами'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(help_text='500mg, 1000IU и т.д.', max_length=50, verbose_name='Дозировка')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Артикул')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='bio_core_website.element', verbose_name='Базовый элемент')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio_core_website.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Вариант продукта',
                'verbose_name_plural': 'Варианты продуктов',
                'unique_together': {('element', 'manufacturer', 'dosage')},
            },
        ),
        migrations.AddField(
            model_name='useranalysis',
            name='recommended_variants',
            field=models.ManyToManyField(blank=True, help_text='Конкретные продукты от производителей', to='bio_core_website.productvariant', verbose_name='Рекомендуемые варианты'),
        ),
    ]
